# Docker Compose for local/production deployment
version: '3.8'

services:
  web:
    build:
context: .
 dockerfile: Dockerfile
    container_name: tafsilk-web
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=TafsilkPlatform
      - Jwt__Audience=TafsilkPlatformUsers
      - Google__client_id=${GOOGLE_CLIENT_ID}
      - Google__client_secret=${GOOGLE_CLIENT_SECRET}
      - Facebook__app_id=${FACEBOOK_APP_ID}
      - Facebook__app_secret=${FACEBOOK_APP_SECRET}
    depends_on:
      - db
    networks:
  - tafsilk-network
  restart: unless-stopped
    healthcheck:
 test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
   timeout: 10s
   retries: 3
      start_period: 40s

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tafsilk-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - tafsilk-network
    restart: unless-stopped

  # Optional: Nginx reverse proxy
  nginx:
  image: nginx:alpine
    container_name: tafsilk-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
networks:
   - tafsilk-network
    restart: unless-stopped

networks:
  tafsilk-network:
    driver: bridge

volumes:
  sqldata:
    driver: local
